fix sqlite version to avoid an installation that have been happening …
lighthouse-labs/node-skeleton pull request #2
Opened 2017-07-21 16:37 UTC by settinghead

…on some students' vagrant machines

2018-05-17 00:10 UTC, vaz requested changes
I don't think there's any reason to keep sqlite3 in here at all. Suggesting we just remove it. Related: lighthouse-labs/2016-web-curriculum-activities#763

2018-05-17 00:11 UTC, vaz commented
Related: lighthouse-labs/2016-web-curriculum-activities#763

2018-06-18 08:48 UTC, Harrisandwich commented
I'm going merge this later this week, because it's small and will at least keep things going smoothly until we go through with removing the dependancy. If anyone objects (@vaz) speak now/before wednesday

2018-10-09 20:27 UTC, daegren requested changes

2018-10-09 20:27 UTC, daegren commented on package.json
> +    "sqlite3": "3.1.4"
Just remove this instead, as per @vaz's comment

2019-07-25 01:55 UTC, closed without merging